[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.params.Depends",
    "fastapi.Query",
    "fastapi.params.Query",
]

[tool.pyright]
venvPath = "."
venv = "venv"

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["app", "."]
norecursedirs = "env/*"
addopts = "-vv -p no:cacheprovider --disable-warnings"
testpaths = ["tests"]
python_files = "test_*.py"

[tool.bandit]
exclude_dirs = ["tests", "__pycache__"]
tests = ["B201", "B301"]
skips = ["B101", "B601"]
